# Generated by Django 4.1 on 2022-09-02 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name of article')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('anons', models.CharField(max_length=50, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of publication')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
